# Generated by Django 4.1.4 on 2022-12-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_accessories_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='weather.category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cold',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cool',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(default='no description', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='hot',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default='no name', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.CharField(default='no photo', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rain',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='snow',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='weather.user'),
        ),
        migrations.AlterField(
            model_name='item',
            name='warm',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='wind',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
